### PR TITLE
Upgrade from upstream bolinfest/plovr bbc3b46010d07b3ba3fec110c5f5d1ab73613f12

### PR DESCRIPTION
**Pull request by akerfoot**

### CODE REVIEW

**Comment by alex-napofearth** [comment]
@cindee-napofearth, I'm not sure if we actually want to pull the trigger on this just yet. I'd like to test it out beforehand.

**Comment by hblanks** [comment]
Aw. What's the fun in that, guys?

**Comment by alex-napofearth** [comment]
Ok, there's a branch with the fixes needed once this version lands in the package archive, so I'm going to go ahead and merge this.

**Comment by cindee-napofearth** [comment]
Sounds good, Ill be building and testing this afternoon

**Pull request merged**
